server:
  port: 8090
  servlet-path: /
logging:
  config: classpath:logback-spring.xml

spring:
  datasource:
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/world?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT&allowMultiQueries=true
      username: "root"
      password: "123456"
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 30
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      web-stat-filter:
        enabled: true
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
        profile-enable: false
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin


mybatis:
  mapperLocations: classpath*:mapping/*Mapper.xml
  typeAliasesPackage: org/jon/lv/domain


#多个地址用逗号分隔 如: host1:2181,host2:2181 -- 必填
regCenter:
  serverList: 127.0.0.1:2181
  namespace: boot-elastic-job

simpleJob:
  cron: 0/30 * * * * ?
  shardingTotalCount: 1
  shardingItemParameters: 0=shanghai

testJob:
  cron: 0/5 * * * * ?
  shardingTotalCount: 1
  shardingItemParameters: 0=shanghai